services:
  gitbox-api:
    container_name: gitbox-api
    build: api
    restart: always
    env_file: .env
    networks: 
      - gitbox
    depends_on:
      - gitbox-redis
  gitbox-redis:
    container_name: gitbox-redis
    image: redis
    restart: always
    networks: 
      - gitbox
  gitbox-web:
    container_name: gitbox-web
    build: 
      context: web
      args: 
        - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
    restart: always
    networks: 
      - gitbox
    ports:
      - 8010:80
networks:
  gitbox:
